### Base URL
@baseURL = http://localhost:3333

### Create user
POST {{baseURL}}/users
Content-Type: application/json

{
  "name": "Mauricio Pinto",
  "email": "mauriciop@cpqd.com.br"
}

### Create meal
POST {{baseURL}}/meals
Content-Type: application/json

{
  "name": "Frango na chapa",
  "description": "Frango frito na frigideira",
  "date": "2025-04-13T01:30:38.286Z",
  "isOnDiet": false
}

### Get meals by each user
GET {{baseURL}}/meals

### Get meal by meal id and each user
GET {{baseURL}}/meals/079a2b9e-2cd7-493d-bcdb-cb17b5a42637

### Edit meal
PATCH {{baseURL}}/meals/079a2b9e-2cd7-493d-bcdb-cb17b5a42637
Content-Type: application/json

{
  "name": "Whey protein",
  "description": "Fazer uma vitamina",
  "date": "2025-04-14T01:30:38.286Z",
  "isOnDiet": true
}

### Delete meal
DELETE {{baseURL}}/meals/079a2b9e-2cd7-493d-bcdb-cb17b5a42637

### Get metrics
GET {{baseURL}}/meals/metrics
